[2024-06-25T12:17:49.168+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T12:17:49.212+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stage_1.run_bronze_job manual__2024-06-25T12:17:43.387578+00:00 [queued]>
[2024-06-25T12:17:49.222+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stage_1.run_bronze_job manual__2024-06-25T12:17:43.387578+00:00 [queued]>
[2024-06-25T12:17:49.222+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-25T12:17:49.237+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_bronze_job> on 2024-06-25 12:17:43.387578+00:00
[2024-06-25T12:17:49.244+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1459) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-25T12:17:49.245+0000] {standard_task_runner.py:63} INFO - Started process 1460 to run task
[2024-06-25T12:17:49.244+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stage_1', 'run_bronze_job', 'manual__2024-06-25T12:17:43.387578+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/kafka_dag.py', '--cfg-path', '/tmp/tmpao8f8qrx']
[2024-06-25T12:17:49.246+0000] {standard_task_runner.py:91} INFO - Job 104: Subtask run_bronze_job
[2024-06-25T12:17:49.260+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-25T12:17:49.292+0000] {task_command.py:426} INFO - Running <TaskInstance: Stage_1.run_bronze_job manual__2024-06-25T12:17:43.387578+00:00 [running]> on host 0b2aef5f9e3a
[2024-06-25T12:17:49.384+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stage_1' AIRFLOW_CTX_TASK_ID='run_bronze_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T12:17:43.387578+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-25T12:17:43.387578+00:00'
[2024-06-25T12:17:49.385+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T12:17:49.415+0000] {docker.py:366} INFO - Starting docker container from image bitnami/spark:latest
[2024-06-25T12:17:49.419+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-06-25T12:17:49.858+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m12:17:49.85 [0m[38;5;2mINFO [0m ==>
[2024-06-25T12:17:49.859+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m12:17:49.85 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami spark container[0m
[2024-06-25T12:17:49.861+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m12:17:49.86 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2024-06-25T12:17:49.862+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m12:17:49.86 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2024-06-25T12:17:49.864+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m12:17:49.86 [0m[38;5;2mINFO [0m ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit [1mhttps://bitnami.com/enterprise[0m
[2024-06-25T12:17:49.865+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m12:17:49.86 [0m[38;5;2mINFO [0m ==>
[2024-06-25T12:17:49.874+0000] {docker.py:436} INFO - 
[2024-06-25T12:17:52.313+0000] {docker.py:436} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-06-25T12:17:52.424+0000] {docker.py:436} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2024-06-25T12:17:52.433+0000] {docker.py:436} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2024-06-25T12:17:52.436+0000] {docker.py:436} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-7ef98e48-7f6c-4551-bc1b-bdf42900b9fb;1.0
[2024-06-25T12:17:52.436+0000] {docker.py:436} INFO - confs: [default]
[2024-06-25T12:17:54.349+0000] {docker.py:436} INFO - found org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.0 in central
[2024-06-25T12:17:54.739+0000] {docker.py:436} INFO - found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.0 in central
[2024-06-25T12:17:54.803+0000] {docker.py:436} INFO - found org.apache.kafka#kafka-clients;2.8.1 in central
[2024-06-25T12:17:54.868+0000] {docker.py:436} INFO - found org.lz4#lz4-java;1.8.0 in central
[2024-06-25T12:17:54.931+0000] {docker.py:436} INFO - found org.xerial.snappy#snappy-java;1.1.8.4 in central
[2024-06-25T12:17:55.083+0000] {docker.py:436} INFO - found org.slf4j#slf4j-api;1.7.32 in central
[2024-06-25T12:17:56.626+0000] {docker.py:436} INFO - found org.apache.hadoop#hadoop-client-runtime;3.3.2 in central
[2024-06-25T12:17:56.746+0000] {docker.py:436} INFO - found org.spark-project.spark#unused;1.0.0 in central
[2024-06-25T12:17:56.864+0000] {docker.py:436} INFO - found org.apache.hadoop#hadoop-client-api;3.3.2 in central
[2024-06-25T12:17:57.078+0000] {docker.py:436} INFO - found commons-logging#commons-logging;1.1.3 in central
[2024-06-25T12:17:57.124+0000] {docker.py:436} INFO - found com.google.code.findbugs#jsr305;3.0.0 in central
[2024-06-25T12:17:58.147+0000] {docker.py:436} INFO - found org.apache.commons#commons-pool2;2.11.1 in central
[2024-06-25T12:17:58.173+0000] {docker.py:436} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.0/spark-sql-kafka-0-10_2.12-3.3.0.jar ...
[2024-06-25T12:17:58.249+0000] {docker.py:436} INFO - [SUCCESSFUL ] org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.0!spark-sql-kafka-0-10_2.12.jar (86ms)
[2024-06-25T12:17:58.261+0000] {docker.py:436} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.3.0/spark-token-provider-kafka-0-10_2.12-3.3.0.jar ...
[2024-06-25T12:17:58.280+0000] {docker.py:436} INFO - [SUCCESSFUL ] org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.0!spark-token-provider-kafka-0-10_2.12.jar (29ms)
[2024-06-25T12:17:58.291+0000] {docker.py:436} INFO - downloading https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.8.1/kafka-clients-2.8.1.jar ...
[2024-06-25T12:17:58.915+0000] {docker.py:436} INFO - [SUCCESSFUL ] org.apache.kafka#kafka-clients;2.8.1!kafka-clients.jar (633ms)
[2024-06-25T12:17:58.927+0000] {docker.py:436} INFO - downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar ...
[2024-06-25T12:17:58.942+0000] {docker.py:436} INFO - [SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.0!jsr305.jar (24ms)
[2024-06-25T12:17:58.955+0000] {docker.py:436} INFO - downloading https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar ...
[2024-06-25T12:17:58.980+0000] {docker.py:436} INFO - [SUCCESSFUL ] org.apache.commons#commons-pool2;2.11.1!commons-pool2.jar (36ms)
[2024-06-25T12:17:58.989+0000] {docker.py:436} INFO - downloading https://repo1.maven.org/maven2/org/spark-project/spark/unused/1.0.0/unused-1.0.0.jar ...
[2024-06-25T12:17:58.999+0000] {docker.py:436} INFO - [SUCCESSFUL ] org.spark-project.spark#unused;1.0.0!unused.jar (18ms)
[2024-06-25T12:17:59.010+0000] {docker.py:436} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.2/hadoop-client-runtime-3.3.2.jar ...
[2024-06-25T12:18:02.473+0000] {docker.py:436} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-client-runtime;3.3.2!hadoop-client-runtime.jar (3472ms)
[2024-06-25T12:18:02.485+0000] {docker.py:436} INFO - downloading https://repo1.maven.org/maven2/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar ...
[2024-06-25T12:18:02.577+0000] {docker.py:436} INFO - [SUCCESSFUL ] org.lz4#lz4-java;1.8.0!lz4-java.jar (103ms)
[2024-06-25T12:18:02.591+0000] {docker.py:436} INFO - downloading https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar ...
[2024-06-25T12:18:02.808+0000] {docker.py:436} INFO - [SUCCESSFUL ] org.xerial.snappy#snappy-java;1.1.8.4!snappy-java.jar(bundle) (229ms)
[2024-06-25T12:18:02.817+0000] {docker.py:436} INFO - downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar ...
[2024-06-25T12:18:02.831+0000] {docker.py:436} INFO - [SUCCESSFUL ] org.slf4j#slf4j-api;1.7.32!slf4j-api.jar (21ms)
[2024-06-25T12:18:02.842+0000] {docker.py:436} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.2/hadoop-client-api-3.3.2.jar ...
[2024-06-25T12:18:04.938+0000] {docker.py:436} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-client-api;3.3.2!hadoop-client-api.jar (2105ms)
[2024-06-25T12:18:04.950+0000] {docker.py:436} INFO - downloading https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar ...
[2024-06-25T12:18:04.968+0000] {docker.py:436} INFO - [SUCCESSFUL ] commons-logging#commons-logging;1.1.3!commons-logging.jar (28ms)
[2024-06-25T12:18:04.969+0000] {docker.py:436} INFO - :: resolution report :: resolve 5725ms :: artifacts dl 6808ms
[2024-06-25T12:18:04.970+0000] {docker.py:436} INFO - :: modules in use:
[2024-06-25T12:18:04.971+0000] {docker.py:436} INFO - com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2024-06-25T12:18:04.972+0000] {docker.py:436} INFO - commons-logging#commons-logging;1.1.3 from central in [default]
	org.apache.commons#commons-pool2;2.11.1 from central in [default]
	org.apache.hadoop#hadoop-client-api;3.3.2 from central in [default]
	org.apache.hadoop#hadoop-client-runtime;3.3.2 from central in [default]
[2024-06-25T12:18:04.973+0000] {docker.py:436} INFO - org.apache.kafka#kafka-clients;2.8.1 from central in [default]
	org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.0 from central in [default]
[2024-06-25T12:18:04.974+0000] {docker.py:436} INFO - org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.0 from central in [default]
[2024-06-25T12:18:04.975+0000] {docker.py:436} INFO - org.lz4#lz4-java;1.8.0 from central in [default]
[2024-06-25T12:18:04.975+0000] {docker.py:436} INFO - org.slf4j#slf4j-api;1.7.32 from central in [default]
[2024-06-25T12:18:04.976+0000] {docker.py:436} INFO - org.spark-project.spark#unused;1.0.0 from central in [default]
[2024-06-25T12:18:04.976+0000] {docker.py:436} INFO - org.xerial.snappy#snappy-java;1.1.8.4 from central in [default]
[2024-06-25T12:18:04.977+0000] {docker.py:436} INFO - ---------------------------------------------------------------------
[2024-06-25T12:18:04.977+0000] {docker.py:436} INFO - |                  |            modules            ||   artifacts   |
[2024-06-25T12:18:04.978+0000] {docker.py:436} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
[2024-06-25T12:18:04.978+0000] {docker.py:436} INFO - |      default     |   12  |   12  |   12  |   0   ||   12  |   12  |
	---------------------------------------------------------------------
[2024-06-25T12:18:04.982+0000] {docker.py:436} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-7ef98e48-7f6c-4551-bc1b-bdf42900b9fb
[2024-06-25T12:18:04.982+0000] {docker.py:436} INFO - confs: [default]
[2024-06-25T12:18:05.051+0000] {docker.py:436} INFO - 12 artifacts copied, 0 already retrieved (56631kB/69ms)
[2024-06-25T12:18:05.380+0000] {docker.py:436} INFO - 24/06/25 12:18:05 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-06-25T12:18:06.860+0000] {docker.py:436} INFO - Traceback (most recent call last):
  File "/opt/bitnami/spark/scripts/spark_bronze_layer.py", line 12, in <module>
[2024-06-25T12:18:06.860+0000] {docker.py:436} INFO - from sqlalchemy import create_engine
ModuleNotFoundError
[2024-06-25T12:18:06.861+0000] {docker.py:436} INFO - : No module named 'sqlalchemy'
[2024-06-25T12:18:06.932+0000] {docker.py:436} INFO - 24/06/25 12:18:06 INFO ShutdownHookManager: Shutdown hook called
[2024-06-25T12:18:06.934+0000] {docker.py:436} INFO - 24/06/25 12:18:06 INFO ShutdownHookManager: Deleting directory /tmp/spark-2ab04f1d-8161-45ff-905a-d8fd0903fecf
[2024-06-25T12:18:07.427+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T12:18:07.437+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-proxy:2375/v1.45/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 371, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 398, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 456, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http://docker-proxy:2375/v1.45/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmp4swlgt67")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 509, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 380, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 444, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-06-25T12:18:07.444+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Stage_1, task_id=run_bronze_job, run_id=manual__2024-06-25T12:17:43.387578+00:00, execution_date=20240625T121743, start_date=20240625T121749, end_date=20240625T121807
[2024-06-25T12:18:07.458+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 104 for task run_bronze_job (Docker container failed: {'StatusCode': 1}; 1460)
[2024-06-25T12:18:07.505+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-25T12:18:07.524+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T12:18:07.526+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
