[2024-06-24T13:30:53.868+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T13:30:53.912+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: use_PythonOperator.kafka_create_topic manual__2024-06-24T13:30:52.660294+00:00 [queued]>
[2024-06-24T13:30:53.925+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: use_PythonOperator.kafka_create_topic manual__2024-06-24T13:30:52.660294+00:00 [queued]>
[2024-06-24T13:30:53.926+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-24T13:30:53.945+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): kafka_create_topic> on 2024-06-24 13:30:52.660294+00:00
[2024-06-24T13:30:53.956+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=185) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-24T13:30:53.958+0000] {standard_task_runner.py:63} INFO - Started process 186 to run task
[2024-06-24T13:30:53.956+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'use_PythonOperator', 'kafka_create_topic', 'manual__2024-06-24T13:30:52.660294+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/kafka_dag.py', '--cfg-path', '/tmp/tmpwtzc0nec']
[2024-06-24T13:30:53.958+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask kafka_create_topic
[2024-06-24T13:30:53.975+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-24T13:30:54.014+0000] {task_command.py:426} INFO - Running <TaskInstance: use_PythonOperator.kafka_create_topic manual__2024-06-24T13:30:52.660294+00:00 [running]> on host 8e89500c3118
[2024-06-24T13:30:54.118+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='use_PythonOperator' AIRFLOW_CTX_TASK_ID='kafka_create_topic' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T13:30:52.660294+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-24T13:30:52.660294+00:00'
[2024-06-24T13:30:54.119+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T13:30:54.155+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T13:30:54.155+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: create_kafka_topic() missing 4 required positional arguments: 'bootstrap_servers', 'topic_name', 'num_partitions', and 'replication_factor'
[2024-06-24T13:30:54.168+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=use_PythonOperator, task_id=kafka_create_topic, run_id=manual__2024-06-24T13:30:52.660294+00:00, execution_date=20240624T133052, start_date=20240624T133053, end_date=20240624T133054
[2024-06-24T13:30:54.182+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task kafka_create_topic (create_kafka_topic() missing 4 required positional arguments: 'bootstrap_servers', 'topic_name', 'num_partitions', and 'replication_factor'; 186)
[2024-06-24T13:30:54.212+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-24T13:30:54.242+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T13:30:54.247+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
